### ISSUE TITLE
New Icon in Yosemite Dark Mode

### ISSUE THREAD

**Issue by xythobuz** [timoschlueter/RocketBeans.TV-Sendeplan#37] opened 2015-04-13 20:32 UTC
On my non-retina machine the TV in the new logo is nearly invisible when in Yosemites new Dark Mode. See this screenshot:

![screen shot 2015-04-13 at 22 26 12](https://cloud.githubusercontent.com/assets/557828/7124848/9152c49e-e22c-11e4-80aa-bb89b4c92598.png)

I would prefer the border to be white. To achieve this it may be enough [to set the icon as template](http://indiestack.com/2014/10/yosemites-dark-mode/)...?

**Comment by TheVaan** [comment] 2015-04-24 10:22
Should be fixed in #39 
Setting Icon as Template is already done, but the problem is, that the live icon is not completely dark - seems like OS X can recognize that and ignores coloring the icon for dark mode.

![bildschirmfoto 2015-04-24 um 12 25 44](https://cloud.githubusercontent.com/assets/1108485/7317130/7858895c-ea7d-11e4-96db-b08a42bac189.png)

#39 has two bugs:
- switching to dark mode while a live show is streaming doesn't change the icon instantly! You need to wait until the next refresh of program plan (by default 60 seconds)
- icon looks ugly in highlighted mode (on click)

**Closed as completed** 2016-10-11 05:04 UTC
